var lst = ["lastname","firstname","agennt",
"Abad","Fernando","The MAS+ Agency",
"Abbott","Cory","Dynamic Sports Group",
"Abreu","Albert","Vayner Sports",
"Abreu","Bryan",
"Abreu","Jose","ISE Baseball",
"Acevedo","Domingo","Wasserman",
"Acuna","Ronald","Rep 1 Baseball",
"Adam","Jason","Platinum Sports",
"Adames","Cristhian","A & F Sports Agency",
"Adames","Willy","CAA Sports",
"Adams","Austin D.","Beverly Hills Sports Council",
"Adams","Austin L.","Full Circle Sports Management",
"Adams","Chance",
"Adams","Matt","Wasserman",
"Adams","Riley",
"Adduci","Jim",
"Adell","Jo","Boras Corporation",
"Adon","Joan",
"Adrianza","Ehire","Warner Sports Management",
"Agrazal","Dario",
"Aguilar","Jesus","MVP Sports Group",
"Aguilar","Miguel",
"Ahmed","Nick","Excel Sports Management",
"Akin","Keegan",
"Akiyama","Shogo","Excel Sports Management",
"Alaniz","R.J.","Octagon",
"Albers","Andrew","True Gravity Baseball",
"Albers","Matt","SSG Baseball",
"Alberto","Hanser","CAA Sports",
"Albies","Ozzie","SportsMeter",
"Alcala","Jorge","Optimum Baseball Associates",
"Alcantara","Sandy","CAA Sports",
"Alcantara","Sergio","Quality Control Sports",
"Alcantara","Victor",
"Alexander","Scott","Apex Baseball",
"Alexander","Tyler","SSG Baseball",
"Alexy","A.J.",
"Alfaro","Jorge","CAA Sports",
"Alford","Anthony","Jet Sports Management",
"Allard","Kolby","Excel Sports Management",
"Allen","Austin","SportsMeter",
"Allen","Cody","Meister Sports Management",
"Allen","Greg","CAA Sports",
"Allen","Logan",
"Allgeyer","Nick",
"Almonte","Abraham","ISE Baseball",
"Almonte","Yency","Rosenhaus Sports Representation",
"Almora","Albert","Magnus Sports",
"Alonso","Pete","Apex Baseball",
"Alonso","Yonder","MVP Sports Group",
"Altavilla","Dan","Marquez Athlete",
"Altherr","Aaron","All Bases Covered Sports Management",
"Altuve","Jose","Boras Corporation",
"Alvarado","Jose","OL Baseball Group LLC",
"Alvarez","Eddy",
"Alvarez","Jose","Wasserman",
"Alvarez","Yordan","MVP Sports Group",
"Alzolay","Adbert","Octagon",
"Amburgey","Trey",
"Anderson","Brett","Excel Sports Management",
"Anderson","Brian","CAA Sports",
"Anderson","Chase","Hub Sports Management",
"Anderson","Cody","GSE Worldwide",
"Anderson","Drew",
"Anderson","Ian","ACES",
"Anderson","Justin",
"Anderson","Nick","Gaeta Sports Management",
"Anderson","Shaun","Jet Sports Management",
"Anderson","Tanner","Total Sports",
"Anderson","Tim","Reynolds Sports Management",
"Anderson","Tyler","GSE Worldwide",
"Andreoli","John",
"Andriese","Matt","Beverly Hills Sports Council",
"Andrus","Elvis","Boras Corporation",
"Andujar","Miguel","The MAS+ Agency",
"Antone","Tejay","Warner Sports Management",
"Apostel","Sherten",
"Aquino","Aristides","Rep 1 Baseball",
"Arano","Victor",
"Araujo","Pedro","Rep 1 Baseball",
"Arauz","Jonathan","Fernando Gonzalez","MAS+ Agency",
"Archer","Chris","VC Sports Group",
"Arcia","Orlando","MVP Sports Group",
"Arenado","Nolan","Wasserman",
"Arihara","Kohei",
"Armenteros","Rogelio",
"Armstrong","Shawn","ISE Baseball",
"Arozarena","Randy","Boras Corporation",
"Arraez","Luis","MVP Sports Group",
"Arrieta","Jake","Boras Corporation",
"Arroyo","Christian","O'Connell Sports Management",
"Arteaga","Humberto","Octagon",
"Ashby","Aaron",
"Astudillo","Willians",
"Austin","Tyler","Ballengee Group",
"Avelino","Abiatal",
"Avila","Alex","Excel Sports Management",
"Avila","Pedro",
"Avilan","Luis","SPS Sports Group",
"Axford","John","Beverly Hills Sports Council",
"Bacus","Dakota","Agency 1 Sports",
"Baddoo","Akil","Apex Baseball",
"Bader","Harrison","Vayner Sports",
"Baez","Javier","Wasserman",
"Baez","Michel",
"Baez","Pedro","Nova Sports Agency",
"Baez","Sandy","Octagon",
"Bailey","Brandon","Rep 1 Baseball",
"Bailey","Homer","Excel Sports Management",
"Baker","Bryan",
"Baldonado","Alberto",
"Banda","Anthony","ALIGND Sports Agency",
"Banuelos","Manny",
"Baragar","Caleb","Wasserman",
"Bard","Daniel","ISE Baseball",
"Bard","Luke","ISE Baseball",
"Barlow","Joe",
"Barlow","Scott","Warner Sports Management",
"Barnes","Austin","ACES",
"Barnes","Charlie",
"Barnes","Jacob",
"Barnes","Matt","ISE Baseball",
"Barnette","Tony","Wasserman",
"Barnhart","Tucker","Ballengee Group",
"Baron","Steve","The MAS+ Agency",
"Barraclough","Kyle","PSI Sports Management",
"Barreda","Manny",
"Barrera","Luis","Octagon",
"Barrera","Tres","Ballengee Group",
"Barreto","Franklin",
"Barrett","Aaron","Excel Sports Management",
"Barrett","Jake","Octagon",
"Barria","Jaime","Octagon",
"Bart","Joey","Excel Sports Management",
"Basabe","Luis Alexander",
"Bashlor","Tyler","Jet Sports Management",
"Bass","Anthony","Beverly Hills Sports Council",
"Bassitt","Chris","Meister Sports Management",
"Bauer","Trevor","Luba Sports and ZS Sports",
"Bauers","Jake","VC Sports Group",
"Baumann","Mike",
"Bautista","Gerson","Z-Axis Sports",
"Baz","Shane","Excel Sports Management",
"Bazardo","Eduard",
"Beasley","Jeremy",
"Beaty","Matt","Ballengee Group",
"Beckham","Gordon","CAA Sports",
"Beckham","Tim","Wasserman",
"Bednar","David","Ballengee Group",
"Bedrosian","Cam",
"Beede","Tyler","ACES",
"Beeks","Jalen","Frontline",
"Beer","Seth",
"Bell","Josh","Boras Corporation",
"Bellatti","Andrew",
"Bellinger","Cody","Boras Corporation",
"Belt","Brandon","Excel Sports Management",
"Bemboom","Anthony","Sterling Sports Management",
"Bender","Anthony",
"Benintendi","Andrew","Excel Sports Management",
"Benjamin","Wes",
"Bergen","Travis","Sterling Sports Management",
"Berrios","Jose","Wasserman",
"Berti","Jonathon","Ball Players Agency",
"Betances","Dellin","WME Baseball",
"Bettinger","Alec",
"Bettis","Chad","CAA Sports",
"Betts","Mookie","VC Sports Group",
"Biagini","Joe",
"Bichette","Bo","CAA Sports",
"Bickford","Phil","Rep 1 Baseball",
"Biddle","Jesse","Apex Baseball",
"Bieber","Shane","Rosenhaus Sports Representation",
"Bielak","Brandon","Jack Toffey",
"Biggio","Cavan","Excel Sports Management",
"Bird","Greg","WME Baseball",
"Bird","Kyle",
"Bishop","Braden","Boras Corporation",
"Blach","Ty","Sports Pro Services",
"Black","Ray","Ballengee Group",
"Blackburn","Paul","Apex Baseball",
"Blackmon","Charlie","ACES",
"Blandino","Alex","CAA Sports",
"Blankenhorn","Travis",
"Blazek","Michael","All Bases Covered Sports Management",
"Bleier","Richard","Vision Sports",
"Blevins","Jerry","Excel Sports Management",
"Blewett","Scott",
"Bogaerts","Xander","Boras Corporation",
"Bohm","Alec","Boras Corporation",
"Bolanos","Ronald","Magnus Sports",
"Bolt","Skye","Jet Sports Management",
"Bonifacio","Emilio","Mato Sports Management",
"Bonifacio","Jorge","ISE Baseball",
"Borucki","Ryan","ISE Baseball",
"Boshers","Buddy",
"Bostick","Akeem",
"Bote","David","Magnus Sports",
"Bour","Justin","Marc Kligman",
"Bourjos","Peter","Republik Sports",
"Bourque","James","Octagon",
"Bowden","Ben",
"Bowman","Matt","ZS Sports",
"Boxberger","Brad","Paragon Sports International",
"Boyd","Matthew","Boras Corporation",
"Brach","Brad","Big League Management Company","LLC",
"Bracho","Silvino",
"Bradford","Chasen","Pierce Sports and Entertainment",
"Bradley","Archie","BBI Sports Group",
"Bradley","Bobby",
"Bradley Jr.","Jackie","Boras Corporation",
"Brantley","Michael","Excel Sports Management",
"Brantly","Rob","Lagardere Sports",
"Brasier","Ryan","ALIGND Sports Agency",
"Brault","Steven","Warner Sports Management",
"Braun","Ryan","CAA Sports",
"Braymer","Ben","Ballengee Group",
"Brebbia","John","Icon Sports Management",
"Bregman","Alex","Boras Corporation",
"Brennan","Brandon",
"Brentz","Jake","The Bledsoe Agency",
"Brewer","Colten","Pro Agents","Inc.",
"Brice","Austin","VC Sports Group",
"Briceno","Jose",
"Brigham","Jeff","CAA Sports",
"Brinson","Lewis","Excel Sports Management",
"Brito","Socrates","The MAS+ Agency",
"Britton","Zack","Boras Corporation",
"Brogdon","Connor","PSI Sports Management",
"Brooks","Aaron","Paragon Sports International",
"Brosseau","Michael","Icon Sports Management",
"Brothers","Rex","Jet Sports Management",
"Brown","Seth","Ball Players Agency",
"Broxton","Keon","Reynolds Sports Management",
"Brubaker","J.T.",
"Bruce","Jay","Excel Sports Management",
"Bruihl","Justin",
"Brujan","Vidal",
"Bryant","Kris","Boras Corporation",
"Bubic","Kris","Apex Baseball",
"Buchholz","Clay","ISE Baseball",
"Buchter","Ryan",
"Buehler","Walker","Excel Sports Management",
"Bukauskas","J.B.",
"Bumgarner","Madison","VC Sports Group",
"Bummer","Aaron","O'Connell Sports Management",
"Bundy","Dylan","BBI Sports Group",
"Burdi","Nick","Apex Baseball",
"Burdi","Zack","Apex Baseball",
"Burger","Jake","The Bledsoe Agency",
"Burke","Brock","Apex Baseball",
"Burnes","Corbin","CAA Sports",
"Burns","Andrew",
"Burr","Ryan",
"Burrows","Beau","Frontline",
"Bush","Matt",
"Butera","Drew","David Schwartz",
"Buttrey","Ty",
"Buxton","Byron","Jet Sports Management",
"Cabrera","Asdrubal","Mato Sports Management",
"Cabrera","Edward",
"Cabrera","Genesis",
"Cabrera","Melky","Rep 1 Baseball",
"Cabrera","Miguel","ISE Baseball",
"Cahill","Trevor","John Boggs & Associates",
"Cain","Lorenzo","All Bases Covered Sports Management",
"Calhoun","Kole","PSI Sports Management",
"Calhoun","Willie","MVP Sports Group",
"Camarena","Daniel",
"Camargo","Johan","Octagon",
"Cameron","Daz","Boras Corporation",
"Campbell","Eric","Octagon",
"Campbell","Paul",
"Campusano","Luis","Ballengee Group",
"Candelario","Jeimer","Paul Kinzer",
"Canha","Mark","CAA Sports",
"Canning","Griffin","Wasserman",
"Cano","Robinson","Roc Nation Sports",
"Carasiti","Matt",
"Caratini","Victor","MDR Sports Management",
"Carle","Shane","Paragon Sports International",
"Carlson","Dylan","ALIGND Sports Agency",
"Carlton","Drew",
"Carpenter","David","Sports One Athlete Management",
"Carpenter","Matt","SSG Baseball",
"Carpenter","Ryan",
"Carrasco","Carlos","ACES",
"Carroll","Cody",
"Casali","Curt","Beverly Hills Sports Council",
"Cashner","Andrew","CAA Sports",
"Castano","Daniel","Truth Sports",
"Castellani","Ryan","Wasserman",
"Castellanos","Humberto","Full Circle Sports Management",
"Castellanos","Nick","SportsMeter",
"Castillo","Diego",
"Castillo","Erick",
"Castillo","Ivan",
"Castillo","Jose",
"Castillo","Luis","Republik Sports",
"Castillo","Welington","ACES",
"Castillo","Wilkin",
"Castro","Anthony",
"Castro","Harold","The MAS+ Agency",
"Castro","Jason","ISE Baseball",
"Castro","Kervin",
"Castro","Miguel","Ballengee Group",
"Castro","Rodolfo",
"Castro","Starlin","Magnus Sports",
"Castro","Willi","ISE Baseball",
"Cave","Jake","Ballengee Group",
"Cease","Dylan","Boras Corporation",
"Cedeno","Xavier","MDR Sports Management",
"Cederlind","Blake",
"Celestino","Gilberto",
"Centeno","Juan","The MAS+ Agency",
"Cervelli","Francisco","Republik Sports",
"Cespedes","Yoenis","Roc Nation Sports",
"Cessa","Luis",
"Chacin","Jhoulys","Rep 1 Baseball",
"Chafin","Andrew","Meister Sports Management",
"Chang","Yu-Cheng","Wasserman",
"Chapman","Aroldis","Magnus Sports",
"Chapman","Matt","Boras Corporation",
"Chargois","J.T.",
"Chatwood","Tyler","Excel Sports Management",
"Chavez","Jesse","Apex Baseball",
"Chavis","Michael","CAA Sports",
"Chen","Wei-Yin","Boras Corporation",
"Chirinos","Robinson","MDR Sports Management",
"Chirinos","Yonny","MDR Sports Management",
"Chisholm","Jazz","Roc Nation Sports",
"Choi","Ji-Man","GSM LLC",
"Choo","Shin-Soo","Ballengee Group",
"Cimber","Adam","Shahpar Sports",
"Cishek","Steve","Jet Sports Management",
"Cisnero","Jose","Rep 1 Baseball",
"Ciuffo","Nick","Frontline",
"Civale","Aaron","Jack Toffey",
"Clarke","Taylor","Ballengee Group",
"Clase","Emmanuel","Nova Sports Agency",
"Claudio","Alex","MDR Sports Management",
"Clay","Sam","Ballengee Group",
"Cleavinger","Garrett",
"Clement","Ernie",
"Clevinger","Mike","ACES",
"Clippard","Tyler","Excel Sports Management",
"Cobb","Alex","Beverly Hills Sports Council",
"Cody","Kyle",
"Cole","A.J.","CAA Sports",
"Cole","Gerrit","Boras Corporation",
"Cole","Taylor",
"Coleman","Dylan",
"Colina","Edwar","Rep 1 Baseball",
"Collins","Tim","Octagon",
"Collins","Zack","MVP Sports Group",
"Colome","Alex","Wasserman",
"Colon","Christian","ACES",
"Conforto","Michael","Boras Corporation",
"Conley","Adam","CAA Sports",
"Contreras","Roansy","Rep 1 Baseball",
"Contreras","William","Octagon",
"Contreras","Willson","Octagon",
"Coonrod","Sam","Wasserman",
"Cooper","Garrett","Ballengee Group",
"Corbin","Patrick","ISE Baseball",
"Cordell","Ryan","Rowley Sports Management",
"Cordero","Franchy","Republik Sports",
"Cordero","Jimmy","Octagon",
"Correa","Carlos","Boras Corporation",
"Cortes","Nestor",
"Cotton","Jharel","The Legacy Agency",
"Coulombe","Daniel","Elite Sports Group",
"Court","Ryan",
"Cousins","Jake",
"Covey","Dylan","CAA Sports",
"Cowart","Kaleb","ISE Baseball",
"Cozart","Zack","Excel Sports Management",
"Cozens","Dylan","Octagon",
"Craig","Will","The Bledsoe Agency",
"Crawford","Brandon","Wasserman",
"Crawford","J.P.","Wasserman",
"Crawford","Kutter",
"Crichton","Stefan","MVP Sports Group",
"Crick","Kyle","CAA Sports",
"Crismatt","Nabil",
"Criswell","Cooper",
"Crochet","Garrett","CAA Sports",
"Cron","C.J.","Moye Sports Associates",
"Cron","Kevin","Moye Sports Associates",
"Cronenworth","Jake","CAA Sports",
"Crouse","Hans","Wasserman",
"Crowe","Wil",
"Cruz","Jesus",
"Cruz","Nelson","Bryce Dixon",
"Cruz","Oneil","Vayner Sports",
"Cueto","Johnny","Bryce Dixon",
"Cuevas","Noel",
"Culberson","Charlie","Ballengee Group",
"Curtiss","John",
"Cuthbert","Cheslor","ISE Baseball",
"d'Arnaud","Travis","Wasserman",
"Dahl","David","Excel Sports Management",
"Dalbec","Bobby","CAA Sports",
"Darvish","Yu","Wasserman",
"Davidson","Matt","MVP Sports Group",
"Davidson","Tucker","ISE Baseball",
"Davies","Zach","Boras Corporation",
"Davis","Austin","KHG Sports Management",
"Davis","Chris","Boras Corporation",
"Davis","J.D.","ALIGND Sports Agency",
"Davis","Jaylin","Beverly Hills Sports Council",
"Davis","Johnny",
"Davis","Jonathan","Beverly Hills Sports Council",
"Davis","Khris","Octagon",
"Davis","Rajai","GSE Worldwide",
"Davis","Rookie","Full Circle Sports Management",
"Davis","Taylor","John Boggs & Associates",
"Davis","Wade","Jet Sports Management",
"Dawson","Ronnie",
"Dayton","Grant","KVA Sports",
"Daza","Yonathan","Munger English Sports Management",
"de Geus","Brett","Excel Sports Management",
"De Goti","Alex",
"De Jong","Chase",
"De La Cruz","Bryan","Rep 1 Baseball",
"De Leon","Jose","Boras Corporation",
"De Los Santos","Enyel","Octagon",
"Dean","Austin",
"deGrom","Jacob","VC Sports Group",
"Deichmann","Greg",
"DeJong","Paul","C.L. Rocks Corporation",
"Del Pozo","Miguel",
"Delmonico","Nicky","CAA Sports",
"Demeritte","Travis","ACES",
"Dermody","Matt","KVA Sports",
"Descalso","Daniel","Steve Canter Pro Edge Sports",
"DeSclafani","Anthony","VC Sports Group",
"DeShields","Delino","Wasserman",
"Desmond","Ian","CAA Sports",
"Despaigne","Odrisamer","Movement Management Group",
"Detmers","Reid",
"Detwiler","Ross","CAA Sports",
"Devenski","Chris","Boras Corporation",
"Devers","Jose",
"Devers","Rafael","Rep 1 Baseball",
"Diaz","Aledmys","Jaime Torres",
"Diaz","Edwin","Wasserman",
"Diaz","Elias","The MAS+ Agency",
"Diaz","Isan",
"Diaz","Jairo","ISE Baseball",
"Diaz","Jhonathan",
"Diaz","Lewin","CAA Sports",
"Diaz","Miguel",
"Diaz","Yandy","Octagon",
"Diaz","Yennsy","Magnus Sports",
"Dickerson","Alex","Moye Sports Associates",
"Dickerson","Corey","Excel Sports Management",
"Dickson","Brandon","Platinum Sports",
"Diehl","Phillip","Dynamic Sports Group",
"Diekman","Jake","Beverly Hills Sports Council",
"Dietrich","Derek","All Bases Covered Sports Management",
"Difo","Wilmer","Truth Sports",
"Dini","Nick",
"Diplan","Marcos","Rep 1 Baseball",
"Dixon","Brandon","ISE Baseball",
"Dobnak","Randy","Gaeta Sports Management",
"Dohy","Kyle","The Bledsoe Agency",
"Dolis","Rafael","Moye Sports Associates",
"Dominguez","Seranthony",
"Donaldson","Josh","MVP Sports Group",
"Doolittle","Sean","Jason Cook",
"Dorow","Ryan",
"Doval","Camilo",
"Dowdy","Kyle",
"Doyle","Tommy","Total Sports",
"Dozier","Brian","All Bases Covered Sports Management",
"Dozier","Hunter","Warner Sports Management",
"Drake","Oliver","ACES",
"Drury","Brandon","Wasserman",
"Dubon","Mauricio","ALIGND Sports Agency",
"Duda","Lucas","Beverly Hills Sports Council",
"Duffey","Tyler","Ballengee Group",
"Duffy","Danny","ACES",
"Duffy","Matt","TWC Sports",
"Duggar","Steven","ISE Baseball",
"Dugger","Robert",
"Duke","Zach","ISE Baseball",
"Dull","Ryan","Ascend Sports Group",
"Dunn","Justin","CAA Sports",
"Dunn","Mike",
"Dunning","Dane","Jet Sports Management",
"Duplantier","Jon","CAA Sports",
"Duran","Jarren",
"DuRapau","Montana","Agency 1 Sports",
"Duvall","Adam","CAA Sports",
"Dyson","Jarrod","ACES",
"Dyson","Sam","ISE Baseball",
"Eades","Ryan",
"Eaton","Adam","Diamond Sports Management",
"Edman","Tommy","Jonathan Weiss",
"Edwards","Jon","Moye Sports Associates",
"Edwards Jr.","Carl","Ballengee Group",
"Effross","Scott",
"Eflin","Zach","O'Connell Sports Management",
"Eibner","Brett",
"Eickhoff","Jerad","VC Sports Group",
"Elias","Roenis","MDR Sports Management",
"Elledge","Seth","ISE Baseball",
"Ellis","Chris","CAA Sports",
"Ellis","Drew","Boras Corporation",
"Elmore","Jake",
"Emanuel","Kent",
"Encarnacion","Edwin","Rep 1 Baseball",
"Engel","Adam","Icon Sports Management",
"Enns","Dietrich",
"Eovaldi","Nathan","ACES",
"Erlin","Robbie","Apex Baseball",
"Ervin","Phillip","Moye Sports Associates",
"Escobar","Alcides","GSE Worldwide",
"Escobar","Eduardo","DJ Rengifo Y Associates LLC",
"Escobar","Luis",
"Eshelman","Thomas","Ballengee Group",
"Espinal","Raynel",
"Espinal","Santiago",
"Espino","Paolo",
"Estevez","Carlos",
"Estrada","Marco","TWC Sports",
"Estrada","Thairo","MVP Sports Group",
"Evans","Demarcus","Roc Nation Sports",
"Evans","Phillip","CAA Sports",
"Fairbanks","Peter","Republik Sports",
"Fairchild","Stuart",
"Falter","Bailey",
"Familia","Jeurys","ACES",
"Fargas","Johneshwy",
"Faria","Jacob",
"Farmer","Buck",
"Farmer","Kyle","Beverly Hills Sports Council",
"Farrell","Luke","ISE Baseball",
"Fedde","Erick","Boras Corporation",
"Federowicz","Tim","ISE Baseball",
"Feierabend","Ryan","McNamara Baseball Group",
"Feliciano","Mario",
"Feliz","Michael","Octagon",
"Feliz","Neftali","Optimum Baseball Associates",
"Feltner","Ryan",
"Ferguson","Caleb",
"Fernandez","Jose","Boras Corporation",
"Fernandez","Julian",
"Fernandez","Junior","Vayner Sports",
"Festa","Matt",
"Feyereisen","J.P.","Warner Sports Management",
"Fiers","Mike","BASH Baseball",
"Fillmyer","Heath","Gaeta Sports Management",
"Finnegan","Kyle","Warner Sports Management",
"Fisher","Derek",
"Flaa","Jay",
"Flaherty","Jack","CAA Sports",
"Flaherty","Ryan","CAA Sports",
"Fleming","Josh","Republik Sports",
"Fletcher","Aaron","KVA Sports",
"Fletcher","David","Ballengee Group",
"Flexen","Chris","O'Connell Sports Management",
"Flores","Bernardo",
"Flores","Wilmer","McNamara Baseball Group",
"Florial","Estevan",
"Floro","Dylan","Steve Canter Pro Edge Sports",
"Flowers","Tyler","O'Connell Sports Management",
"Flynn","Brian","Sports Pro Services",
"Foley","Jason",
"Foltynewicz","Mike","Excel Sports Management",
"Font","Wilmer","OL Baseball Group LLC",
"Ford","Mike","ZS Sports",
"Forsythe","Logan","PSI Sports Management",
"Fortes","Nick",
"Foster","Matt",
"Fowler","Dexter","Excel Sports Management",
"Fowler","Dustin",
"Fraley","Jake","CAA Sports",
"France","Ty","Reynolds Sports Management",
"Franco","Enderson",
"Franco","Maikel","Octagon",
"Franco","Wander","Manny Paula",
"Frankoff","Seth","CSE",
"Frare","Caleb",
"Frazier","Adam","Bo McKinnis",
"Frazier","Clint","ACES",
"Frazier","Todd","CAA Sports",
"Freeland","Kyle","MSM Sports Management",
"Freeman","Freddie","Excel Sports Management",
"Freeman","Mike","BASH Baseball",
"Freeman","Sam","Roc Nation Sports",
"Freese","David","CAA Sports",
"Freitas","David","PSI Sports Management",
"Frias","Luis",
"Fried","Max","CAA Sports",
"Friedl","TJ","Apex Baseball",
"Fry","Jace","Northwest Sports Management Group",
"Fry","Paul","Wasserman",
"Fuentes","Josh",
"Fulmer","Carson","Icon Sports Management",
"Fulmer","Michael","BBI Sports Group",
"Funkhouser","Kyle","Boras Corporation",
"Gagnon","Drew","ISE Baseball",
"Gale","Rocky",
"Gallagher","Cam","Ryan Ware",
"Gallegos","Giovanny",
"Gallen","Zac","Boras Corporation",
"Gallo","Joey","Boras Corporation",
"Galloway","Isaac",
"Galvis","Freddy","Rep 1 Baseball",
"Gamel","Ben","Jet Sports Management",
"Gant","John","ACES",
"Garcia","Adolis",
"Garcia","Aramis",
"Garcia","Avisail","Mato Sports Management",
"Garcia","Bryan",
"Garcia","Deivi","Rep 1 Baseball",
"Garcia","Edgar",
"Garcia","Greg","Meister Sports Management",
"Garcia","Jarlin","Paul Kinzer",
"Garcia","Jose",
"Garcia","Leury","MDR Sports Management",
"Garcia","Luis","Topline Sports & Entertainment","LLC",
"Garcia","Luis","Topline Sports & Entertainment","LLC",
"Garcia","Luis","Topline Sports & Entertainment","LLC",
"Garcia","Rico","Gaeta Sports Management",
"Garcia","Robel","Quality Control Sports",
"Garcia","Rony",
"Garcia","Yimi","Nova Sports Agency",
"Gardner","Brett","Meister Sports Management",
"Garlick","Kyle",
"Garneau","Dustin","Marc Kligman",
"Garrett","Amir","Boras Corporation",
"Garrett","Braxton","Boras Corporation",
"Garrett","Reed",
"Garton","Ryan",
"Garver","Mitch","ISE Baseball",
"Garza","Justin",
"Garza","Ralph",
"Gausman","Kevin","Tidal Sports Group",
"Gaviglio","Sam","KVA Sports",
"Gearrin","Cory","Bo McKinnis",
"Gennett","Scooter","ISE Baseball",
"Gerber","Joey",
"Gerber","Mike","CAA Sports",
"German","Domingo","Rep 1 Baseball",
"Giambrone","Trent",
"Gibaut","Ian",
"Gibson","Kyle","Rowley Sports Management",
"Gil","Luis",
"Gilbert","Logan",
"Gilbert","Tyler","Ballengee Group",
"Gilbreath","Lucas",
"Giles","Ken","Rowley Sports Management",
"Gilmartin","Sean","Sports One Athlete Management",
"Gimenez","Andres","Rep 1 Baseball",
"Ginkel","Kevin","Ballengee Group",
"Giolito","Lucas","CAA Sports",
"Gittens","Chris",
"Givens","Mychal","Excel Sports Management",
"Glasnow","Tyler","Wasserman",
"Godley","Zack","Sports Pro Services",
"Godoy","Jose",
"Goins","Ryan","Octagon",
"Goldschmidt","Paul","Excel Sports Management",
"Gomber","Austin","Jet Sports Management",
"Gomes","Yan","Jet Sports Management",
"Gomez","Carlos","MVP Sports Group",
"Gomez","Jeanmar","The MAS+ Agency",
"Gonsalves","Stephen","John Boggs & Associates",
"Gonsolin","Tony","Beverly Hills Sports Council",
"Gonzales","Marco","CAA Sports",
"Gonzalez","Carlos","Boras Corporation",
"Gonzalez","Chi Chi","Paragon Sports International",
"Gonzalez","Erik",
"Gonzalez","Gio","CAA Sports",
"Gonzalez","Luis",
"Gonzalez","Marwin","MVP Sports Group",
"Gonzalez","Romy",
"Gonzalez","Victor",
"Goodrum","Niko","Roc Nation Sports",
"Goodwin","Brian","MVP Sports Group",
"Goody","Nick","Octagon",
"Gordon","Alex","Excel Sports Management",
"Gordon","Nick","Beverly Hills Sports Council",
"Gore","Terrance","Warner Sports Management",
"Gose","Anthony","CAA Sports",
"Gosselin","Phil",
"Gott","Trevor","Sports One Athlete Management",
"Goudeau","Ashton","Republik Sports",
"Grace","Matt","Wasserman",
"Grandal","Yasmani","Wasserman",
"Granderson","Curtis","Pro Prospects","Inc.
"Graterol","Brusdar","Boras Corporation",
"Graterol","Juan","Apex Baseball",
"Graveman","Kendall","Sports One Athlete Management",
"Gray","Jon","CAA Sports",
"Gray","Josiah","Icon Sports Management",
"Gray","Sonny","Bo McKinnis",
"Green","Chad","Frontline",
"Green","Zach",
"Greene","Conner","Vayner Sports",
"Greene","Shane","Ballengee Group",
"Gregerson","Luke","O'Connell Sports Management",
"Gregorius","Didi","Excel Sports Management",
"Greiner","Grayson","Beverly Hills Sports Council",
"Greinke","Zack","Excel Sports Management",
"Grichuk","Randal","Excel Sports Management",
"Griffin","Foster","Excel Sports Management",
"Grimm","Justin","The Bledsoe Agency",
"Grisham","Trent","ISE Baseball",
"Grossman","Robbie","Lagardere Sports",
"Grotz","Zac",
"Grullon","Deivy",
"Gsellman","Robert","CAA Sports",
"Guduan","Reymin","Warner Sports Management",
"Guenther","Sean",
"Guerra","Deolis","Rep 1 Baseball",
"Guerra","Javier",
"Guerra","Javy","Reynolds Sports Management",
"Guerra","Junior","MVP Sports Group",
"Guerrero","Tayron","TLA Worldwide",
"Guerrero Jr.","Vladimir","Magnus Sports",
"Guerrieri","Taylor","GSE Worldwide",
"Guilbeau","Taylor","PSI Sports Management",
"Guillorme","Luis","MVP Sports Group",
"Guilmet","Preston",
"Gurriel","Lourdes","Magnus Sports",
"Gurriel","Yuli","Wasserman",
"Gushue","Taylor",
"Gustave","Jandel",
"Gutierrez","Kelvin","Octagon",
"Gutierrez","Vladimir","Octagon",
"Guzman","Jorge","PNY Sports",
"Guzman","Ronald","Boras Corporation",
"Gyorko","Jedd","ACES",
"Haase","Eric","Warner Sports Management",
"Hader","Josh","CAA Sports",
"Hager","Jake","Paragon Sports International",
"Haggerty","Sam",
"Hahn","Jesse","Excel Sports Management",
"Hale","David","ZS Sports",
"Hall","Matt",
"Hamels","Cole","John Boggs & Associates",
"Hamilton","Billy","Wasserman",
"Hamilton","Ian","Northwest Sports Management Group",
"Hammer","JD","Magnus Sports",
"Hampson","Garrett","TWC Sports",
"Hand","Brad","Jet Sports Management",
"Hanhold","Eric",
"Haniger","Mitch","Apex Baseball",
"Hanson","Alen","L.A. Sports Management",
"Happ","Ian","WME Baseball",
"Happ","J.A.","Rogers Sports Management","LLC",
"Hardy","Blaine","Only Baseball Players",
"Harper","Bryce","Boras Corporation",
"Harper","Ryne",
"Harris","Will","Gavin Kahn",
"Harrison","Josh","MSM Sports Management",
"Harrison","Monte","MVP Sports Group",
"Hart","Donnie","Frontline",
"Hart","Kyle","Nello Gamberdino",
"Hartlieb","Geoff","Paragon Sports International",
"Hartman","Ryan",
"Harvey","Hunter",
"Harvey","Joe",
"Harvey","Matt","Boras Corporation",
"Haseley","Adam","Frontline",
"Hatch","Thomas","Moye Sports Associates",
"Hayes","Ke'Bryan","Ballengee Group",
"Hays","Austin","The MAS+ Agency",
"Head","Louis",
"Healy","Ryon","Excel Sports Management",
"Heaney","Andrew","Icon Sports Management",
"Hearn","Taylor","CAA Sports",
"Heasley","Jon",
"Heath","Nick","CAA Sports",
"Hechavarria","Adeiny","Magnus Sports",
"Hedges","Austin","Boras Corporation",
"Heim","Jonah","Frye McCann Sports",
"Heineman","Scott",
"Heineman","Tyler","Beverly Hills Sports Council",
"Heller","Ben","Onyx Sports Management",
"Hellickson","Jeremy","Boras Corporation",
"Helsley","Ryan","Ballengee Group",
"Hembree","Heath","Ballengee Group",
"Hendricks","Kyle","Wasserman",
"Hendriks","Liam","ALIGND Sports Agency",
"Hendrix","Ryan",
"Henry","Payton",
"Hentges","Sam","ISE Baseball",
"Heredia","Guillermo","Magnus Sports",
"Herget","Jimmy","Paragon Sports International",
"Hermosillo","Michael",
"Hernandez","Carlos",
"Hernandez","Cesar","Octagon",
"Hernandez","Darwinzon","Carlos Murcia",
"Hernandez","David","Jason Hoffman",
"Hernandez","Elieser","Elite Sports Group",
"Hernandez","Felix","Octagon",
"Hernandez","Gorkys","SPS Sports Group",
"Hernandez","Jonathan",
"Hernandez","Kike","Wasserman",
"Hernandez","Marco","ISE Baseball",
"Hernandez","Oscar",
"Hernandez","Teoscar","Republik Sports",
"Hernandez","Yadiel",
"Hernandez","Yonny","Nova Sports Agency",
"Herrera","Dilson","The MAS+ Agency",
"Herrera","Kelvin","Republik Sports",
"Herrera","Odubel","Victor Tranquillo",
"Herrera","Rosell","ISE Baseball",
"Herrmann","Chris","Sports Management Partners",
"Hess","David","Total Sports",
"Heuer","Codi","Truth Sports",
"Heyward","Jason","Excel Sports Management",
"Hicks","Aaron","CAA Sports",
"Hicks","John","Full Circle Sports Management",
"Hicks","Jordan","Ballengee Group",
"Higashioka","Kyle","Beverly Hills Sports Council",
"Higgins","P.J.","The Bledsoe Agency",
"Hildenberger","Trevor","Ballengee Group",
"Hill","Cam",
"Hill","Derek","Reynolds Sports Management",
"Hill","Rich","ACES",
"Hill","Tim",
"Hilliard","Sam","Magnus Sports",
"Hirano","Yoshihisa","John Boggs & Associates",
"Hiura","Keston","Klutch Sports",
"Hoerner","Nico","Apex Baseball",
"Hoffman","Jeff","CAA Sports",
"Holaday","Bryan","Lagardere Sports",
"Holder","Jonathan",
"Holland","Derek","Martini Sports Management",
"Holland","Greg","Boras Corporation",
"Holloway","Jordan",
"Holmes","Clay","Jet Sports Management",
"Holt","Brock","Lagardere Sports",
"Honeywell","Brent",
"Hoskins","Rhys","Boras Corporation",
"Hosmer","Eric","Boras Corporation",
"Houck","Tanner","CAA Sports",
"Houser","Adrian","Players Edge Sports Management",
"Howard","Sam","Jet Sports Management",
"Howard","Spencer","Apex Baseball",
"Hoying","Jared","Pro Star Management","Inc.
"Hoyt","James",
"Huang","Wei-Chieh",
"Hudson","Dakota",
"Hudson","Daniel","Jet Sports Management",
"Hudson","Joe","Meister Sports Management",
"Huff","Sam","Boras Corporation",
"Hughes","Jared","ISE Baseball",
"Hultzen","Danny","CAA Sports",
"Hundley","Nick","Athletes First",
"Hunter","Tommy","Moye Sports Associates",
"Hurst","Scott",
"Hutchison","Drew","ACES",
"Iannetta","Chris","Octagon",
"Ibanez","Andy","Quality Control Sports",
"Iglesias","Jose","MVP Sports Group",
"Iglesias","Raisel","Magnus Sports",
"Inciarte","Ender","Octagon",
"India","Jonathan","Meister Sports Management",
"Irvin","Cole",
"Isbel","Kyle","Paragon Sports International",
"Ivey","Tyler",
"Jackson","Alex",
"Jackson","Andre","ACES",
"Jackson","Drew","CAA Sports",
"Jackson","Edwin","ESQ Agency",
"Jackson","Jay","GSI",
"Jackson","Luke","Vayner Sports",
"James","Josh","CAA Sports",
"Jankowski","Travis",
"Jannis","Mickey",
"Jansen","Danny","ISE Baseball",
"Jansen","Kenley","Wasserman",
"Javier","Cristian","MVP Sports Group",
"Jax","Griffin","PSI Sports Management",
"Jay","Jon","CAA Sports",
"Jefferies","Daulton","Apex Baseball",
"Jeffers","Ryan","Ballengee Group",
"Jeffress","Jeremy","Roc Nation Sports",
"Jennings","Dan","ISE Baseball",
"Jerez","Williams",
"Jewell","Jake",
"Jimenez","Dany","PNY Sports",
"Jimenez","Eduardo",
"Jimenez","Eloy","Rep 1 Baseball",
"Jimenez","Joe","ISE Baseball",
"Joe","Connor","John Boggs & Associates",
"Johnson","Brian","Jet Sports Management",
"Johnson","D.J.","Magnus Sports",
"Johnson","Daniel",
"Johnson","Pierce","John Boggs & Associates",
"Jones","Adam","CAA Sports",
"Jones","Damon",
"Jones","JaCoby","Boras Corporation",
"Jones","Jahmai",
"Jones","Nate","Sterling Sports Management",
"Jones","Taylor",
"Joseph","Caleb","PSI Sports Management",
"Joseph","Corban","PSI Sports Management",
"Joyce","Matt","ACES",
"Judge","Aaron","PSI Sports Management",
"Junis","Jakob","Wasserman",
"Junk","Janson",
"Jurado","Ariel",
"Kahnle","Tommy","Ballengee Group",
"Kaminsky","Rob","Excel Sports Management",
"Kang","Jung Ho","Wasserman",
"Kaprielian","James",
"Karinchak","James","Vayner Sports",
"Karns","Nathan",
"Kay","Anthony","CAA Sports",
"Kazmar","Sean",
"Kazmir","Scott","Excel Sports Management",
"Kela","Keone","Robert Fayne",
"Kelenic","Jarred","Wasserman",
"Keller","Brad","Excel Sports Management",
"Keller","Kyle","Nello Gamberdino",
"Keller","Mitch","Excel Sports Management",
"Kelley","Shawn","Frye McCann Sports",
"Kelley","Trevor","C.L. Rocks Corporation",
"Kelly","Carson","Apex Baseball",
"Kelly","Joe","ACES",
"Kelly","Merrill","Apex Baseball",
"Kemp","Matt","Reynolds Sports Management",
"Kemp","Tony","Ballengee Group",
"Kendrick","Howie","Reynolds Sports Management",
"Kennedy","Ian","Boras Corporation",
"Kepler","Max","Apex Baseball",
"Kershaw","Clayton","Excel Sports Management",
"Keuchel","Dallas","Boras Corporation",
"Kickham","Mike","ISE Baseball",
"Kieboom","Carter","Vanguard Sports Group",
"Kiermaier","Kevin","Reynolds Sports Management",
"Kikuchi","Yusei","Boras Corporation",
"Kilome","Franklyn",
"Kim","Ha-Seong","ISE Baseball",
"Kim","Kwang-hyun","John Boggs & Associates",
"Kimbrel","Craig","SportsMeter",
"Kiner-Falefa","Isiah","ALIGND Sports Agency",
"King","John",
"King","Michael",
"Kingery","Scott","PSI Sports Management",
"Kingham","Nick",
"Kinley","Tyler","Paragon Sports International",
"Kinsler","Ian","BBI Sports Group",
"Kintzler","Brandon","Kevin Kohler",
"Kipnis","Jason","Beverly Hills Sports Council",
"Kirilloff","Alex","Boras Corporation",
"Kirk","Alejandro","Vayner Sports",
"Kittredge","Andrew","Paragon Sports International",
"Kivlehan","Patrick","Pro Agents","Inc.
"Kline","Branden",
"Klobosits","Gabe",
"Kluber","Corey","Jet Sports Management",
"Knapp","Andrew","Apex Baseball",
"Knebel","Corey","Excel Sports Management",
"Knehr","Reiss","ACES",
"Knight","Dusten","Big League Management Company","LLC",
"Knizner","Andrew","CAA Sports",
"Koch","Matt",
"Koerner","Brody",
"Kolarek","Adam","Warner Sports Management",
"Kopech","Michael","CAA Sports",
"Kowar","Jackson",
"Kozma","Pete","Excel Sports Management",
"Kramer","Kevin","Apex Baseball",
"Kranick","Max","Ballengee Group",
"Kratz","Erik","Ball Players Agency",
"Krehbiel","Joey",
"Kremer","Dean",
"Kriske","Brooks",
"Krol","Ian","ISE Baseball",
"Kuhl","Chad","ACES",
"Kuhnel","Joel",
"La Stella","Tommy","Beverly Hills Sports Council",
"Ladendorf","Tyler",
"Lagares","Juan","ACES",
"Lail","Brady",
"Lakins","Travis",
"LaMarre","Ryan","Octagon",
"Lamb","Jake","CAA Sports",
"Lambert","Jimmy",
"Lambert","Peter",
"Lamet","Dinelson","MVP Sports Group",
"Lange","Alex",
"Larnach","Trevor","Beverly Hills Sports Council",
"Latz","Jake",
"Lauer","Eric","CAA Sports",
"Laureano","Ramon","Octagon",
"Lavarnway","Ryan","Wasserman",
"Law","Derek","CAA Sports",
"Lawrence","Justin",
"Leake","Mike","Beverly Hills Sports Council",
"LeBlanc","Wade","Icon Sports Management",
"Leclerc","Jose","Munger English Sports Management",
"Lee","Dylan","PSI Sports Management",
"Lee","Khalil",
"Leibrandt","Brandon",
"LeMahieu","DJ","Wasserman",
"Leon","Sandy","The MAS+ Agency",
"Leone","Dominic","ACES",
"Lester","Jon","ACES",
"Lewicki","Artie","McNamara Baseball Group",
"Lewis","Kyle","VC Sports Group",
"Leyba","Domingo","ISE Baseball",
"Leyer","Robinson",
"Lin","Tzu-Wei",
"Lindblom","Josh","GSI",
"Lindor","Francisco","SportsMeter",
"Liriano","Francisco","Wasserman",
"Littell","Zack","CAA Sports",
"Lively","Ben","Meister Sports Management",
"Llovera","Mauricio",
"Loaisiga","Jonathan","ISE Baseball",
"Lobaton","Jose","Athletes X",
"Lobstein","Kyle","Ballengee Group",
"Locastro","Tim","Warner Sports Management",
"Lockett","Walker","O'Connell Sports Management",
"Long","Sammy","ACES",
"Long","Shed","Rep 1 Baseball",
"Longoria","Evan","TWC Sports",
"Lopes","Tim","CAA Sports",
"Lopez","Alejo",
"Lopez","Jack",
"Lopez","Jorge",
"Lopez","Nicky","Octagon",
"Lopez","Otto","BSE Agency Inc.
"Lopez","Pablo","Excel Sports Management",
"Lopez","Reynaldo","CAA Sports",
"Lopez","Yoan","Wasserman",
"Lorenzen","Michael","CAA Sports",
"Loup","Aaron","Beverly Hills Sports Council",
"Lovelady","Richard",
"Lowe","Brandon","The Bledsoe Agency",
"Lowe","Josh","SportsMeter",
"Lowe","Nate","SportsMeter",
"Lowrie","Jed","Excel Sports Management",
"Lowther","Zac","The Bledsoe Agency",
"Lucas","Josh","Total Sports",
"Lucchesi","Joey","CAA Sports",
"Luciano","Elvis","Optimum Baseball Associates",
"Lucroy","Jonathan","Ballengee Group",
"Luetge","Lucas","Frye McCann Sports",
"Lugo","Dawel",
"Lugo","Seth","Ballengee Group",
"Luplow","Jordan","MVP Sports Group",
"Lux","Gavin","Jet Sports Management",
"Luzardo","Jesus","Boras Corporation",
"Lyles","Jordan","Ballengee Group",
"Lynch","Daniel","The Bledsoe Agency",
"Lynn","Lance","Headline Sports Group",
"Lyons","Tyler","Icon Sports Management",
"Machado","Andres",
"Machado","Manny","MVP Sports Group",
"Machin","Vimael",
"Madero","Luis",
"Madrigal","Nick","Wasserman",
"Maeda","Kenta","Wasserman",
"Magill","Matt","PSI Sports Management",
"Mahle","Tyler","ISE Baseball",
"Mahtook","Mikie","CAA Sports",
"Maile","Luke","Meister Sports Management",
"Maldonado","Martin","MVP Sports Group",
"Manaea","Sean","Boras Corporation",
"Mancini","Trey","Frontline",
"Manning","Matt","Boras Corporation",
"Manoah","Alek",
"Mantiply","Joe","ACES",
"Maples","Dillon","CAA Sports",
"Marcano","Tucupita",
"Marchan","Rafael",
"Margevicius","Nick",
"Margot","Manuel","Wasserman",
"Marisnick","Jake","Reynolds Sports Management",
"Markakis","Nick","TWC Sports",
"Markel","Parker","KVA Sports",
"Marmolejos","Jose","CAA Sports",
"Marquez","Brailyn","Nova Sports Agency",
"Marquez","German","L.A. Sports Management",
"Marrero","Deven",
"Marsh","Brandon","ACES",
"Marshall","Evan","ISE Baseball",
"Marte","Jose",
"Marte","Ketel","Quality Control Sports",
"Marte","Luis","California Sports Management",
"Marte","Starling","Rep 1 Baseball",
"Martin","Brett",
"Martin","Chris","ISE Baseball",
"Martin","Corbin",
"Martin","Jason","Roc Nation Sports",
"Martin","Leonys","Wasserman",
"Martin","Richie","ISE Baseball",
"Martin","Russell","Matt Colleran",
"Martinez","Carlos","Octagon",
"Martinez","J.D.","Boras Corporation",
"Martinez","Jose","Octagon",
"Martinez","Nick","Octagon",
"Martinez","Seth",
"Martini","Nick",
"Marvel","James",
"Mateo","Jorge","Quality Control Sports",
"Mathias","Mark","Apex Baseball",
"Mathis","Jeff","Jet Sports Management",
"Mathisen","Wyatt","ALIGND Sports Agency",
"Maton","Nick",
"Maton","Phil","Paragon Sports International",
"Mattson","Isaac",
"Matz","Steven","Icon Sports Management",
"Matzek","Tyler","Rep 1 Baseball",
"May","Dustin","Paragon Sports International",
"May","Trevor","VC Sports Group",
"Maybin","Cameron","Mato Sports Management",
"Mayers","Mike",
"Mayfield","Jack","Beverly Hills Sports Council",
"Mayza","Tim","Ballengee Group",
"Mazara","Nomar","CAA Sports",
"Mazeika","Patrick",
"Mazza","Chris","Nello Gamberdino",
"McBroom","Ryan","ACES",
"McCann","Brian","Jet Sports Management",
"McCann","James","Ballengee Group",
"McCarthy","Jake",
"McCarthy","Joe","CAA Sports",
"McCarthy","Kevin","Pro Agents","Inc.
"McCaughan","Darren",
"McClain","Reggie",
"McClanahan","Shane","Vayner Sports",
"McCormick","Chas",
"McCullers Jr.","Lance","Boras Corporation",
"McCutchen","Andrew","Aegis Sports Management",
"McFarland","T.J.","Octagon",
"McGee","Jake","Wasserman",
"McGowin","Kyle",
"McGuire","Reese","Apex Baseball",
"McHugh","Collin","Moye Sports Associates",
"McKay","Brendan","Apex Baseball",
"McKay","David",
"McKenna","Ryan",
"McKenzie","Triston","Octagon",
"McKinney","Billy","Boras Corporation",
"McKinstry","Zach","Northwest Sports Management Group",
"McMahon","Ryan","Wasserman",
"McNeil","Jeff","TWC Sports",
"McRae","Alex",
"Meadows","Austin","Excel Sports Management",
"Means","John","Wasserman",
"Mears","Nick",
"Medina","Adonis","Boras Corporation",
"Megill","Trevor",
"Megill","Tylor",
"Meisinger","Ryan","ZS Sports",
"Mejia","Adalberto","Rep 1 Baseball",
"Mejia","Erick","Fusion Sports Agency",
"Mejia","Francisco","ISE Baseball",
"Mejia","Humberto","ISE Baseball",
"Mejia","Jean Carlos",
"Mejias-Brean","Seth","Lagardere Sports",
"Melancon","Mark","ACES",
"Mella","Keury","Rep 1 Baseball",
"Melville","Tim","Jason Cook",
"Mendez","Yohander",
"Mendick","Danny","Icon Sports Management",
"Menez","Conner",
"Mengden","Daniel",
"Mercado","Oscar","Excel Sports Management",
"Mercedes","Yermin","L.A. Sports Management",
"Mercer","Jordy","Truth Sports",
"Merrifield","Whit","Warner Sports Management",
"Merryweather","Julian","Warner Sports Management",
"Meyers","Jacob","Wasserman",
"Middleton","Keynan","ACES",
"Mikolas","Miles","Octagon",
"Miley","Wade","O'Connell Sports Management",
"Miller","Andrew","Frontline",
"Miller","Brad","ISE Baseball",
"Miller","Brian",
"Miller","Ian",
"Miller","Justin","Kevin Kohler",
"Miller","Owen",
"Miller","Shelby","Roc Nation Sports",
"Miller","Tyson","Wasserman",
"Mills","Alec","Ballengee Group",
"Mills","Wyatt",
"Milner","Hoby",
"Milone","Tommy","All Bases Covered Sports Management",
"Minaya","Juan",
"Minor","Mike","Jet Sports Management",
"Minter","A.J.","Excel Sports Management",
"Misiewicz","Anthony",
"Mitchell","Bryan","CSE",
"Mize","Casey","The Bledsoe Agency",
"Molina","Yadier","MDR Sports Management",
"Moll","Sam",
"Moncada","Yoan","Quality Control Sports",
"Mondesi","Adalberto","Octagon",
"Moniak","Mickey","Wasserman",
"Montas","Frankie","Boras Corporation",
"Montero","Rafael","GSE Worldwide",
"Montgomery","Jordan","Boras Corporation",
"Montgomery","Mike","Ballengee Group",
"Moore","Andrew",
"Moore","Dylan","Rep 1 Baseball",
"Moore","Matt","Apex Baseball",
"Morales","Kendrys","Wasserman",
"Moran","Brian","Big League Management Company","LLC",
"Moran","Colin","Excel Sports Management",
"Moran","Jovani","MDR Sports Management",
"Morejon","Adrian","Boras Corporation",
"Moreland","Mitch","Paragon Sports International",
"Moreta","Dauri","Nova Sports Agency",
"Morgan","Adam","CAA Sports",
"Morgan","Eli",
"Morimando","Shawn",
"Morin","Mike","Meister Sports Management",
"Moroff","Max",
"Moronta","Reyes","L.A. Sports Management",
"Morrison","Logan","Ballengee Group",
"Morton","Charlie","Jet Sports Management",
"Motter","Taylor","O'Connell Sports Management",
"Mountcastle","Ryan","Apex Baseball",
"Moustakas","Mike","Boras Corporation",
"Mujica","Jose","Quality Control Sports",
"Muller","Kyle","ISE Baseball",
"Mullins","Cedric",
"Muncy","Max","Hub Sports Management",
"Munoz","Andres","Suarez","Gomez & Associates",
"Munoz","Yairo",
"Murphy","Daniel","ACES",
"Murphy","John Ryan","ISE Baseball",
"Murphy","Patrick",
"Murphy","Sean","Rowley Sports Management",
"Murphy","Tom","Ballengee Group",
"Musgrave","Harrison",
"Musgrove","Joe","Full Circle Sports Management",
"Myers","Wil","CAA Sports",
"Nance","Tommy","Full Circle Sports Management",
"Naquin","Tyler","Excel Sports Management",
"Narvaez","Omar","Steve Comte",
"Naughton","Packy",
"Navarreto","Brian",
"Naylor","Josh","ISE Baseball",
"Negron","Kristopher",
"Neidert","Nick","CAA Sports",
"Nelson","Jimmy","CAA Sports",
"Nelson","Kyle","MVP Sports Group",
"Nelson","Nick",
"Neris","Hector","Octagon",
"Neshek","Pat","Meister Sports Management",
"Neuse","Sheldon","Octagon",
"Neverauskas","Dovydas",
"Nevin","Tyler",
"Newberry","Jake","Ballengee Group",
"Newcomb","Sean","Klutch Sports",
"Newman","Kevin","Jonathan Weiss",
"Newsome","Ljay","KHG Sports Management",
"Nicasio","Juan","El Juego Sports Management",
"Nido","Tomas",
"Nimmo","Brandon","Boras Corporation",
"Nittoli","Vinny","Gaeta Sports Management",
"Noesi","Hector","ACES",
"Nogosek","Stephen","John Shinn",
"Nogowski","John","Optimum Baseball Associates",
"Nola","Aaron","Paragon Sports International",
"Nola","Austin","Paragon Sports International",
"Nolin","Sean","Lagardere Sports",
"Noll","Jake","Agency 1 Sports",
"Nootbaar","Lars",
"Norris","Daniel","Excel Sports Management",
"Northcraft","Aaron",
"Norwood","James","Meister Sports Management",
"Nottingham","Jacob",
"Nova","Ivan","GSE Worldwide",
"Nunez","Darien",
"Nunez","Dom","ALIGND Sports Agency",
"Nunez","Eduardo","ISE Baseball",
"Nunez","Renato","Octagon",
"O'Brien","Peter",
"O'Brien","Riley",
"O'Day","Darren","Ballengee Group",
"O'Grady","Brian",
"O'Hearn","Ryan",
"O'Neill","Tyler","Boras Corporation",
"O'Rourke","Ryan","Sterling Sports Management",
"Ober","Bailey",
"Oberg","Scott","Big League Management Company","LLC",
"Odom","Joseph",
"Odor","Rougned","Beverly Hills Sports Council",
"Odorizzi","Jake","Excel Sports Management",
"Oh","Seung Hwan",
"Ohtani","Shohei","CAA Sports",
"Okert","Steven","Pro Agents","Inc.
"Oliva","Jared",
"Olivares","Edward",
"Olson","Matt","Jet Sports Management",
"Olson","Tyler","Ball Players Agency",
"Ona","Jorge",
"Orf","Nathan",
"Ort","Kaleb","Nello Gamberdino",
"Ortega","Oliver",
"Ortega","Rafael",
"Ortiz","Luis","Reynolds Sports Management",
"Osich","Josh","Ballengee Group",
"Osuna","Jose","ISE Baseball",
"Osuna","Roberto","Vayner Sports",
"Oswalt","Corey","John Boggs & Associates",
"Otero","Dan","ACES",
"Ottavino","Adam","WME Baseball",
"Otto","Glenn","ACES",
"Overton","Connor","KHG Sports Management",
"Oviedo","Johan","CAA Sports",
"Oviedo","Luis",
"Owen","Hunter",
"Owings","Chris","ACES",
"Ozuna","Marcell","CAA Sports",
"Pache","Cristian","Rep 1 Baseball",
"Paddack","Chris","Boras Corporation",
"Padlo","Kevin",
"Pagan","Emilio","Ballengee Group",
"Palacios","Josh",
"Palka","Daniel","Ballengee Group",
"Palumbo","Joe",
"Panik","Joe","Jet Sports Management",
"Pannone","Thomas",
"Paredes","Enoli",
"Paredes","Isaac","CAA Sports",
"Park","Hoy Jun",
"Parker","Blake","Meister Sports Management",
"Parker","Jarrett","CAA Sports",
"Parra","Gerardo","Octagon",
"Parsons","Wes","Full Circle Sports Management",
"Patino","Luis",
"Patton","Spencer","Nello Gamberdino",
"Paulino","David","Optimum Baseball Associates",
"Paxton","James","Boras Corporation",
"Payamps","Joel",
"Payano","Pedro",
"Payne","Tyler","Gaeta Sports Management",
"Payton","Mark","Octagon",
"Pazos","James",
"Peacock","Brad","ACES",
"Peacock","Matt","Gaeta Sports Management",
"Pearce","Steve","Excel Sports Management",
"Pearson","Nate","Excel Sports Management",
"Pederson","Joc","Excel Sports Management",
"Pedroia","Dustin","ACES",
"Peguero","Elvis",
"Pena","Felix",
"Pence","Hunter","Beverly Hills Sports Council",
"Peralta","David","ACES",
"Peralta","Freddy","Rep 1 Baseball",
"Peralta","Wandy","ISE Baseball",
"Peralta","Wily","GSE Worldwide",
"Peraza","Jose","ISE Baseball",
"Perdomo","Angel",
"Perdomo","Geraldo","Madden Sports Group",
"Perdomo","Luis","Octagon",
"Perez","Cionel","Octagon",
"Perez","Francisco",
"Perez","Hector","Optimum Baseball Associates",
"Perez","Hernan","Octagon",
"Perez","Martin","Octagon",
"Perez","Michael","MDR Sports Management",
"Perez","Oliver","Boras Corporation",
"Perez","Roberto","MDR Sports Management",
"Perez","Salvador","Beverly Hills Sports Council",
"Peters","Dillon",
"Peters","DJ",
"Peterson","David","CAA Sports",
"Peterson","Dustin","Excel Sports Management",
"Peterson","Jace","ISE Baseball",
"Peterson","Tim",
"Petit","Yusmeiro","Godoy Sports",
"Petricka","Jake","Republik Sports",
"Pham","Tommy","Vayner Sports",
"Phegley","Josh","Meister Sports Management",
"Phelps","David","Jet Sports Management",
"Phillips","Brett","O'Connell Sports Management",
"Phillips","Evan","Steve Canter Pro Edge Sports",
"Pillar","Kevin","All Bases Covered Sports Management",
"Pina","Manny","Rep 1 Baseball",
"Pinder","Chad","Ballengee Group",
"Pineda","Michael","ISE Baseball",
"Pinto","Ricardo","L.A. Sports Management",
"Pirela","Jose","ISE Baseball",
"Piscotty","Stephen","CAA Sports",
"Pivetta","Nick","CAA Sports",
"Plawecki","Kevin","ACES",
"Plesac","Zach","CAA Sports",
"Plutko","Adam","CAA Sports",
"Poche","Colin","ISE Baseball",
"Polanco","Gregory","Octagon",
"Polanco","Jorge","Octagon",
"Pollock","A.J.","Excel Sports Management",
"Pomeranz","Drew","CAA Sports",
"Ponce","Cody","Excel Sports Management",
"Ponce de Leon","Daniel","Paragon Sports International",
"Pop","Zach",
"Poppen","Sean","Ballengee Group",
"Porcello","Rick","Excel Sports Management",
"Posey","Buster","CAA Sports",
"Poteet","Cody",
"Pounders","Brooks","John Boggs & Associates",
"Poyner","Bobby",
"Pozo","Yohel",
"Prado","Martin","GSE Worldwide",
"Pressly","Ryan","Ballengee Group",
"Price","David","Bo McKinnis",
"Profar","Jurickson","Boras Corporation",
"Pruitt","Austin",
"Puello","Cesar","Rep 1 Baseball",
"Puig","Yasiel","Leona Sports",
"Pujols","Albert","MVP Sports Group",
"Puk","A.J.","ISE Baseball",
"Quackenbush","Kevin","Full Circle Sports Management",
"Quantrill","Cal","Excel Sports Management",
"Quezada","Johan",
"Quijada","Jose","Rep 1 Baseball",
"Quinn","Roman","Roc Nation Sports",
"Quintana","Jose","Wasserman",
"Rainey","Tanner",
"Raleigh","Cal",
"Raley","Brooks","CAA Sports",
"Raley","Luke",
"Ramirez","Erasmo","ISE Baseball",
"Ramirez","Hanley","Wasserman",
"Ramirez","Harold","MVP Sports Group",
"Ramirez","JC",
"Ramirez","Jose","Republik Sports",
"Ramirez","Neil","The Bledsoe Agency",
"Ramirez","Nick",
"Ramirez","Noe","Ballengee Group",
"Ramirez","Roel","Dynamic Sports Group",
"Ramirez","Yefry",
"Ramirez","Yohan",
"Ramos","AJ",
"Ramos","Edubray",
"Ramos","Henry",
"Ramos","Wilson","Octagon",
"Ramsey","Matt",
"Rasmussen","Drew",
"Ravelo","Rangel",
"Ray","Corey",
"Ray","Robbie","VC Sports Group",
"Rea","Colin","Sterling Sports Management",
"Read","Raudy","Octagon",
"Realmuto","J.T.","CAA Sports",
"Reddick","Josh","ACES",
"Reed","A.J.","Wasserman",
"Reed","Cody","Jet Sports Management",
"Reed","Jake",
"Reed","Michael",
"Reetz","Jakson","Wasserman",
"Refsnyder","Rob","PSI Sports Management",
"Reid-Foley","Sean","Jet Sports Management",
"Reininger","Zac","ISE Baseball",
"Reks","Zach",
"Rendon","Anthony","Boras Corporation",
"Renfroe","Hunter",
"Rengifo","Luis","MVP Sports Group",
"Reyes","Alex","Octagon",
"Reyes","Franmil","Optimum Baseball Associates",
"Reyes","Gerardo",
"Reyes","Pablo",
"Reyes","Victor","ISE Baseball",
"Reynolds","Bryan","CAA Sports",
"Reynolds","Mark","Ballengee Group",
"Reynolds","Matt","Frye McCann Sports",
"Rhame","Jacob","Beverly Hills Sports Council",
"Richard","Clayton","ISE Baseball",
"Richards","Garrett","ISE Baseball",
"Richards","Trevor","Apex Baseball",
"Rickard","Joey","GSE Worldwide",
"Riddle","J.T.","Meister Sports Management",
"Ridings","Stephen",
"Riley","Austin","ALIGND Sports Agency",
"Rios","Edwin","Excel Sports Management",
"Rios","Yacksel","Gavin Kahn",
"Rivas","Alfonso",
"Rivas","Webster",
"Rivera","Emmanuel",
"Rivera","Rene","MDR Sports Management",
"Rivera","Yadiel",
"Rivero","Sebastian",
"Rizzo","Anthony","Sports One Athlete Management",
"Roark","Tanner","MVP Sports Group",
"Robert","Luis","Magnus Sports",
"Robertson","Daniel","MVP Sports Group",
"Robertson","David","Self-Represented",
"Robinson","Drew",
"Robles","Hansel","Wasserman",
"Robles","Victor","Republik Sports",
"Robson","Jacob",
"Rodgers","Brady",
"Rodgers","Brendan","Excel Sports Management",
"Rodney","Fernando","Octagon",
"Rodon","Carlos","Boras Corporation",
"Rodriguez","Chris",
"Rodriguez","Dereck","Gavin Kahn",
"Rodriguez","Eduardo","Mato Sports Management",
"Rodriguez","Jefry",
"Rodriguez","Joely","L.A. Sports Management",
"Rodriguez","Jose",
"Rodriguez","Manuel De Jesus",
"Rodriguez","Nivaldo",
"Rodriguez","Richard","MDR Sports Management",
"Rodriguez","Ronny",
"Rodriguez","Sean","MVP Sports Group",
"Roe","Chaz","Apex Baseball",
"Rogers","Jake","Ballengee Group",
"Rogers","Josh",
"Rogers","Taylor","Frontline",
"Rogers","Trevor","PSI Sports Management",
"Rogers","Tyler","Frontline",
"Rojas","Jose",
"Rojas","Josh","ISE Baseball",
"Rojas","Miguel","Beverly Hills Sports Council",
"Romano","Jordan","VC Sports Group",
"Romano","Sal","Wasserman",
"Romero","Fernando",
"Romero","Jhon",
"Romero","JoJo","PSI Sports Management",
"Romero","Seth","Boras Corporation",
"Romine","Andrew","Moye Sports Associates",
"Romine","Austin","Moye Sports Associates",
"Romo","Sergio","Meister Sports Management",
"Rondon","Angel","MDR Sports Management",
"Rondon","Hector","Octagon",
"Rondon","Jose",
"Rooker","Brent","The Bledsoe Agency",
"Rortvedt","Ben","Wasserman",
"Rosa","Adonis",
"Rosario","Amed","Octagon",
"Rosario","Eddie","Roc Nation Sports",
"Rosario","Randy","Movement Management Group",
"Rosenthal","Trevor","Boras Corporation",
"Ross","Joe","Wasserman",
"Ross","Tyson","Wasserman",
"Rosscup","Zac","Magnus Sports",
"Rosso","Ramon","MDR Sports Management",
"Rowen","Ben",
"Rucker","Michael",
"Ruf","Darin","Vanguard Sports Group",
"Ruiz","Jose","OL Baseball Group LLC",
"Ruiz","Keibert","Boras Corporation",
"Ruiz","Rio",
"Rumbelow","Nick","Octagon",
"Rusin","Chris","Sports One Athlete Management",
"Russell","Addison","Boras Corporation",
"Ryan","Joe",
"Ryan","Kyle","Frontline",
"Ryu","Hyun-Jin","Boras Corporation",
"Sabathia","CC","Roc Nation Sports",
"Sadler","Casey","Ballengee Group",
"Sadzeck","Connor",
"Saladino","Tyler",
"Salas","Fernando","Paragon Sports International",
"Salazar","Danny","Jay Alou",
"Sale","Chris","Jet Sports Management",
"Samardzija","Jeff","Wasserman",
"Sampson","Adrian","Apex Baseball",
"Sanabria","Carlos",
"Sanchez","Aaron","Boras Corporation",
"Sanchez","Adrian",
"Sanchez","Ali",
"Sanchez","Anibal","Mato Sports Management",
"Sanchez","Cristopher",
"Sanchez","Gary","The MAS+ Agency",
"Sanchez","Jesus",
"Sanchez","Miguel",
"Sanchez","Ricardo",
"Sanchez","Sixto","Boras Corporation",
"Sanchez","Yolmer","MVP Sports Group",
"Sandlin","Nick",
"Sandoval","Pablo","Beverly Hills Sports Council",
"Sandoval","Patrick","Wasserman",
"Sanmartin","Reiver",
"Sano","Miguel","Octagon",
"Santana","Carlos","Octagon",
"Santana","Danny","Mato Sports Management",
"Santana","Dennis","Optimum Baseball Associates",
"Santana","Domingo","Wasserman",
"Santana","Edgar",
"Santana","Ervin","Jay Alou",
"Santander","Anthony","GSE Worldwide",
"Santiago","Hector","Excel Sports Management",
"Santillan","Tony","Boras Corporation",
"Santos","Antonio",
"Santos","Gregory",
"Saucedo","Tayler",
"Sawamura","Hirokazu","John Boggs & Associates",
"Sborz","Josh","McNamara Baseball Group",
"Sceroler","Mac",
"Schebler","Scott","Jim McDowell",
"Scherzer","Max","Boras Corporation",
"Schlitter","Brian","Magnus Sports",
"Schmidt","Clarke","Excel Sports Management",
"Schoop","Jonathan","Boras Corporation",
"Schreiber","John",
"Schrock","Max","Icon Sports Management",
"Schultz","Jaime","CAA Sports",
"Schwarber","Kyle","Excel Sports Management",
"Schwindel","Frank","Pro Agents","Inc.
"Scott","Robby","Meister Sports Management",
"Scott","Tanner",
"Scott","Tayler","PSI Sports Management",
"Scrubb","Andre",
"Seabold","Conner",
"Seager","Corey","Boras Corporation",
"Seager","Kyle","Jet Sports Management",
"Segura","Jean","CAA Sports",
"Selman","Sam","CAA Sports",
"Semien","Marcus","Boras Corporation",
"Senzatela","Antonio","Republik Sports",
"Senzel","Nick","Boras Corporation",
"Severino","Luis","Rep 1 Baseball",
"Severino","Pedro","Republik Sports",
"Sewald","Paul","ISE Baseball",
"Shafer","Justin","Apex Baseball",
"Sharp","Sterling","Octagon",
"Shaw","Bryan","CAA Sports",
"Shaw","Chris","Excel Sports Management",
"Shaw","Travis","Meister Sports Management",
"Shawaryn","Mike",
"Sheets","Gavin",
"Sheffield","Jordan",
"Sheffield","Justus","Bo McKinnis",
"Shepherd","Chandler","Full Circle Sports Management",
"Sherfy","Jimmie","PSI Sports Management",
"Sherriff","Ryan",
"Shoemaker","Matt","Beverly Hills Sports Council",
"Short","Zack",
"Shreve","Chasen","CAA Sports",
"Shuck","J.B.",
"Sierra","Magneuris",
"Simmons","Andrelton","ISE Baseball",
"Sims","Lucas","TWC Sports",
"Singer","Brady","Excel Sports Management",
"Sipp","Tony","The Bledsoe Agency",
"Siri","Jose",
"Sisco","Chance","VC Sports Group",
"Sittinger","Brandyn",
"Skaggs","Tyler","CAA Sports",
"Skoglund","Eric","ACES",
"Skole","Matt","Jet Sports Management",
"Skubal","Tarik","Boras Corporation",
"Slater","Austin","Ballengee Group",
"Slegers","Aaron","Octagon",
"Smeltzer","Devin","ISE Baseball",
"Smith","Burch","Truth Sports",
"Smith","Caleb","Ballengee Group",
"Smith","Dominic","Roc Nation Sports",
"Smith","Drew","MVP Sports Group",
"Smith","Joe","Excel Sports Management",
"Smith","Josh",
"Smith","Josh D.",
"Smith","Kevan","Fusion Sports Agency",
"Smith","Kevin","The Bledsoe Agency",
"Smith","Mallex","Roc Nation Sports",
"Smith","Pavin","Excel Sports Management",
"Smith","Riley","Ballengee Group",
"Smith","Will","Apex Baseball",
"Smith","Will","CAA Sports",
"Smith Jr.","Dwight","Wasserman",
"Smoak","Justin","The Bledsoe Agency",
"Smyly","Drew","Frontline",
"Snead","Kirby","Warner Sports Management",
"Sneed","Cy","Apex Baseball",
"Snell","Blake","Boras Corporation",
"Snyder","Nick",
"Sobotka","Chad","ISE Baseball",
"Sogard","Eric","Octagon",
"Solak","Nick","CAA Sports",
"Solano","Donovan","PTSG",
"Solarte","Yangervis","GSE Worldwide",
"Soler","Jorge","MVP Sports Group",
"Solomon","Peter","Warner Sports Management",
"Soria","Joakim","Oscar Suarez",
"Soroka","Mike","ISE Baseball",
"Sosa","Edmundo","Octagon",
"Soto","Elliot","Marc Kligman",
"Soto","Gregory","Munger English Sports Management",
"Soto","Juan","Boras Corporation",
"Souza Jr.","Steven","Moye Sports Associates",
"Spangenberg","Cory","Jet Sports Management",
"Sparkman","Glenn",
"Speier","Gabe","Apex Baseball",
"Spitzbarth","Shea","ACES",
"Springer","George","Excel Sports Management",
"Springs","Jeffrey",
"St. John","Locke",
"Stallings","Jacob","Bo McKinnis",
"Stamets","Eric","MSM Sports Management",
"Stammen","Craig","Paragon Sports International",
"Stanek","Ryne","MVP Sports Group",
"Stanton","Giancarlo","Wasserman",
"Starling","Bubba","Boras Corporation",
"Stashak","Cody",
"Stassi","Max","Wasserman",
"Staumont","Josh","Excel Sports Management",
"Steckenrider","Drew","True Gravity Baseball",
"Steele","Justin","Wasserman",
"Stephan","Trevor",
"Stephenson","Robert","Apex Baseball",
"Stephenson","Tyler","ACES",
"Stevenson","Andrew","Ballengee Group",
"Stewart","Brock","Sterling Sports Management",
"Stewart","Christin","Boras Corporation",
"Stewart","DJ","Boras Corporation",
"Stewart","Kohl","Frontline",
"Stiever","Jonathan","CAA Sports",
"Stock","Robert","Wasserman",
"Stokes Jr.","Troy",
"Story","Trevor","Wasserman",
"Strahm","Matt","ACES",
"Straily","Dan","Apex Baseball",
"Strange-Gordon","Dee","Rep 1 Baseball",
"Strasburg","Stephen","Boras Corporation",
"Stratton","Chris","Bo McKinnis",
"Straw","Myles","Frontline",
"Strickland","Hunter","All Bases Covered Sports Management",
"Strider","Spencer",
"Stripling","Ross","Beverly Hills Sports Council",
"Stroman","Marcus","Excel Sports Management",
"Strop","Pedro","Quality Control Sports",
"Stubbs","Garrett","Boras Corporation",
"Stumpf","Daniel","Full Circle Sports Management",
"Suarez","Andrew",
"Suarez","Eugenio","Octagon",
"Suarez","Jose","ISE Baseball",
"Suarez","Ranger","L.A. Sports Management",
"Sucre","Jesus","Elite Sports Group",
"Suero","Wander","Rep 1 Baseball",
"Sulser","Cole","Full Circle Sports Management",
"Susac","Andrew","GSE Worldwide",
"Suter","Brent","Diamond Sports Management",
"Suzuki","Ichiro","John Boggs & Associates",
"Suzuki","Kurt","ALIGND Sports Agency",
"Swanson","Dansby","Excel Sports Management",
"Swanson","Erik","Pro Star Management","Inc.
"Swarzak","Anthony","Jet Sports Management",
"Swihart","Blake","O'Connell Sports Management",
"Syndergaard","Noah","CAA Sports",
"Szapucki","Thomas","SportsMeter",
"Taillon","Jameson","Excel Sports Management",
"Tanaka","Masahiro","Excel Sports Management",
"Tapia","Domingo","Optimum Baseball Associates",
"Tapia","Raimel","MVP Sports Group",
"Tarpley","Stephen",
"Tate","Dillon","CAA Sports",
"Tatis Jr.","Fernando","MVP Sports Group",
"Tauchman","Mike","Meister Sports Management",
"Taveras","Leody",
"Taylor","Beau","Ball Players Agency",
"Taylor","Blake","ISE Baseball",
"Taylor","Chris","Meister Sports Management",
"Taylor","Josh",
"Taylor","Michael A.","ALIGND Sports Agency",
"Taylor","Tyrone","Wasserman",
"Teheran","Julio","Mato Sports Management",
"Tejada","Ruben","Agency 1 Sports",
"Tejeda","Anderson","Republik Sports",
"Tellez","Rowdy","Bryce Dixon",
"Tepera","Ryan","All Bases Covered Sports Management",
"Terry","Curtis",
"Thaiss","Matt","Pro Agents","Inc.
"Thames","Eric","Apex Baseball",
"Thielbar","Caleb","Octagon",
"Thomas","Dillon",
"Thomas","Lane","Jet Sports Management",
"Thompson","Keegan",
"Thompson","Mason",
"Thompson","Ryan",
"Thompson","Trayce","Wasserman",
"Thompson","Zach","Meister Sports Management",
"Thornburg","Tyler","ACES",
"Thornton","Trent","Jet Sports Management",
"Thorpe","Lewis","Paragon Sports International",
"Tice","Ty",
"Tilson","Charlie",
"Tinoco","Jesus","Rep 1 Baseball",
"Tom","Ka'ai",
"Tomas","Yasmany","Jay Alou",
"Tomlin","Josh","Meister Sports Management",
"Topa","Justin",
"Toro","Abraham",
"Torrens","Luis","ISE Baseball",
"Torres","Carlos","KVA Sports",
"Torres","Gleyber","Octagon",
"Torreyes","Ronald",
"Toussaint","Touki","Boras Corporation",
"Tovar","Wilfredo","Magnus Sports",
"Trammell","Taylor","CAA Sports",
"Travis","Sam","Octagon",
"Treinen","Blake","Apex Baseball",
"Trejo","Alan",
"Trevino","Jose","Paragon Sports International",
"Triggs","Andrew","CAA Sports",
"Trivino","Lou","Steve Canter Pro Edge Sports",
"Tromp","Chadwick","BSE Agency Inc.
"Tropeano","Nick","The Bledsoe Agency",
"Trout","Mike","Landis Baseball Group",
"Trumbo","Mark","Wasserman",
"Tsutsugo","Yoshitomo","Wasserman",
"Tucker","Cole","MVP Sports Group",
"Tucker","Kyle","Excel Sports Management",
"Tuivailala","Sam","Apex Baseball",
"Tulowitzki","Troy","TWC Sports",
"Turley","Nik","ISE Baseball",
"Turnbull","Spencer",
"Turner","Justin","Vayner Sports",
"Turner","Trea","CAA Sports",
"Tyler","Kyle","Nello Gamberdino",
"Uceta","Edwin","Sterling Sports Management",
"Underwood Jr.","Duane","Octagon",
"Upton","Justin","Reynolds Sports Management",
"Urena","Jose","Rep 1 Baseball",
"Urena","Richard","Octagon",
"Urias","Julio","Boras Corporation",
"Urias","Luis","CAA Sports",
"Urias","Ramon",
"Urquidy","Jose","Full Circle Sports Management",
"Urshela","Giovanny","Rep 1 Baseball",
"Valaika","Pat",
"Valdez","Cesar",
"Valdez","Framber","Octagon",
"Valdez","Phillips",
"Valera","Breyvic",
"VanMeter","Josh","Sterling Sports Management",
"Vargas","Ildemaro",
"Vargas","Jason","CAA Sports",
"Varsho","Daulton","Martini Sports Management",
"Vasquez","Andrew",
"Vaughn","Andrew",
"Vazquez","Christian","MDR Sports Management",
"Vazquez","Felipe","Magnus Sports",
"Velasquez","Vince","Boras Corporation",
"Velazquez","Andrew","CAA Sports",
"Velazquez","Hector",
"Venditte","Pat","Marc Kligman",
"Venters","Jonny","Jet Sports Management",
"Verdugo","Alex","MVP Sports Group",
"VerHagen","Drew","ISE Baseball",
"Verlander","Justin","ISE Baseball",
"Vesia","Alex","Rep 1 Baseball",
"Vest","Will",
"Vieira","Thyago",
"Vierling","Matt",
"Vilade","Ryan",
"Villar","Jonathan","ACES",
"Viloria","Meibrys",
"Vincent","Nick","PSI Sports Management",
"Vizcaino","Arodys","ISE Baseball",
"Vogelbach","Daniel","ISE Baseball",
"Vogt","Stephen","All Bases Covered Sports Management",
"Voit","Luke","Excel Sports Management",
"Volquez","Edinson","Wasserman",
"Vosler","Jason",
"Voth","Austin",
"Votto","Joey","MVP Sports Group",
"Wacha","Michael","CAA Sports",
"Waddell","Brandon",
"Wade","Konner","Agency 1 Sports",
"Wade","LaMonte","Ballengee Group",
"Wade","Tyler","Paragon Sports International",
"Waguespack","Jacob","Beverly Hills Sports Council",
"Wahl","Bobby",
"Wainwright","Adam","Aegis Sports Management",
"Walden","Marcus","Full Circle Sports Management",
"Walding","Mitch",
"Walker","Christian","Boras Corporation",
"Walker","Jeremy","ACES",
"Walker","Neil","Excel Sports Management",
"Walker","Taijuan","Excel Sports Management",
"Wallach","Chad","PSI Sports Management",
"Walls","Taylor","ACES",
"Walsh","Jared","ISE Baseball",
"Walton","Donnie",
"Wang","Wei-Chung","Boras Corporation",
"Wantz","Andrew","Nello Gamberdino",
"Ward","Taylor","Wasserman",
"Warren","Adam","Full Circle Sports Management",
"Warren","Art","KHG Sports Management",
"Warren","Austin","Ballengee Group",
"Watkins","Spenser","Gaeta Sports Management",
"Watson","Tony","Boras Corporation",
"Weathers","Ryan",
"Weaver","Luke","Boras Corporation",
"Webb","Jacob","KHG Sports Management",
"Webb","Logan","ACES",
"Webb","Tyler","Beverly Hills Sports Council",
"Weber","Ryan","Warner Sports Management",
"Webster","Allen","Wasserman",
"Weems","Jordan",
"Weigel","Patrick",
"Welker","Colton",
"Wells","Alexander",
"Wells","Tyler",
"Wendelken","J.B.","Ascend Sports Group",
"Wendle","Joey","Excel Sports Management",
"Wheeler","Zack","Jet Sports Management",
"White","Eli",
"White","Evan","True Gravity Baseball",
"White","Mitchell","Apex Baseball",
"White","Tyler","Ballengee Group",
"Whitefield","Aaron","Gaeta Sports Management",
"Whitley","Kodi",
"Whitlock","Garrett",
"Wick","Rowan",
"Widener","Taylor","Beverly Hills Sports Council",
"Wieck","Brad","CAA Sports",
"Wieters","Matt","Boras Corporation",
"Wilkerson","Aaron","Paragon Sports International",
"Wilkerson","Steve","Ballengee Group",
"Williams","Austen",
"Williams","Devin","Rep 1 Baseball",
"Williams","Justin","Roc Nation Sports",
"Williams","Luke",
"Williams","Mason",
"Williams","Nick","Boras Corporation",
"Williams","Taylor","Northwest Sports Management Group",
"Williams","Trevor","John Boggs & Associates",
"Williamson","Mac","CAA Sports",
"Wilson","Alex","ISE Baseball",
"Wilson","Bobby","Jet Sports Management",
"Wilson","Bryse","Steve Canter Pro Edge Sports",
"Wilson","Cody",
"Wilson","Jacob",
"Wilson","Justin","ACES",
"Wingenter","Trey","Ballengee Group",
"Winker","Jesse","Excel Sports Management",
"Winkler","Dan","MVP Sports Group",
"Wisdom","Patrick","Apex Baseball",
"Wisler","Matt","Excel Sports Management",
"Wittgren","Nick","John Shinn",
"Wojciechowski","Asher","ISE Baseball",
"Wolters","Tony","VC Sports Group",
"Wong","Connor",
"Wong","Kean","PSI Sports Management",
"Wong","Kolten","PSI Sports Management",
"Wood","Alex","ACES",
"Wood","Hunter","ALIGND Sports Agency",
"Woodford","Jake","Excel Sports Management",
"Woodruff","Brandon","McKinnis Sports",
"Workman","Brandon","CAA Sports",
"Wotherspoon","Matt",
"Wright","Kyle","CAA Sports",
"Wright","Mike",
"Wright","Steven",
"Wynns","Austin","Ball Players Agency",
"Yacabonis","Jimmy","Ballengee Group",
"Yajure","Miguel","Moye Sports Associates",
"Yamaguchi","Shun","Wasserman",
"Yamamoto","Jordan","PSI Sports Management",
"Yang","Hyeon-jong",
"Yarbrough","Ryan","Excel Sports Management",
"Yardley","Eric","CAA Sports",
"Yastrzemski","Mike","Jack Toffey",
"Yates","Kirby","Beverly Hills Sports Council",
"Yelich","Christian","Paragon Sports International",
"Ynoa","Gabriel","GSE Worldwide",
"Ynoa","Huascar",
"Young","Alex","Wasserman",
"Young","Andy","Ballengee Group",
"Zagunis","Mark",
"Zamora","Daniel",
"Zavala","Seby",
"Zerpa","Angel",
"Zeuch","T.J.","Truth Sports",
"Zimmer","Bradley","ISE Baseball",
"Zimmer","Kyle","ISE Baseball",
"Zimmerman","Ryan","CAA Sports",
"Zimmermann","Bruce","Ballengee Group",
"Zimmermann","Jordan","ISE Baseball",
"Zobrist","Ben","Octagon",
"Zuber","Tyler","Full Circle Sports Management",
"Zunino","Mike","Jet Sports Management"
]